---
- name: Playbook de instalacion de la aplicacion 2048 en un servidor apache
  hosts: all
  become: true
  
  roles:
    - 'roles/webserver'
    - 'roles/dbserver'
    - role: deploy
      vars:
        src_file: /home/tux/Downloads/2048.tar.bz2