    - name: Comprobar conectividad
      ansible.builtin.ping:

    - name: Instalar apache
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: true

    - name: Instalar mariadb
      ansible.builtin.apt:
        name: mariadb-server
        state: present

    - name: Desinstalar htop
      ansible.builtin.apt:
        name: htop
        state: absent

    - name: Aplicar plantilla apache
      ansible.builtin.template:
        src: templates/templateJ2.j2
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
    
    - name: Extraer aplicacion 2048
      ansible.builtin.unarchive:
        src: "~/Downloads/2048.tar.bz2"
        dest: "/var/www/html"
        owner: root
        group: root