---
- name: Playbook de instalacion de cosas
  hosts: all
  become: true

  tasks:
    - name: Comprobar conectividad
      ansible.builtin.ping:
    
    - name: Ejecucion en debian
      when: ansible_facts['os_family'] == 'Debian'
      block:
        - name: Instalar apache en debian
          ansible.builtin.apt:
            name: apache2
            state: present
      
        - name: Instalar mariadb en Debian
          ansible.builtin.apt:
            name: mariadb-server
            state: present

    - name: Ejecucion en Redhat
      when: ansible_facts['os_family'] == 'RedHat'
      block:
        - name: Instalar apache en Redhat
          ansible.builtin.yum:
            name: httpd
            state: present

        - name: Start apache
          ansible.builtin.service:
            name: httpd
            state: started
        
        - name: Instalar mariadb en Redhat
          ansible.builtin.yum:
            name: mariadb-server
            state: present

    - name: Aplicar plantilla apache
      ansible.builtin.template:
        src: templates/templateJ2.j2
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
    
    - name: Extraer aplicacion 2048
      ansible.builtin.unarchive:
        src: "/home/tux/Downloads/2048.tar.bz2"
        dest: "/var/www/html"
        owner: root
        group: root