---
- name: Playbook de instalacion de cosas
  hosts: fedora
  become: true

  tasks:
    - name: Comprobar conectividad
      ansible.builtin.ping:

    - name: Instalar apache
      ansible.builtin.dnf:
        name: httpd
        state: latest
        update_cache: yes

    - name: Instalar mariadb
      ansible.builtin.dnf:
        name: mariadb-server
        state: latest

    - name: Desinstalar htop
      ansible.builtin.dnf:
        name: htop
        state: absent

    - name: Aplicar plantilla apache
      ansible.builtin.template:
        src: templates/templateJ2.j2
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
    
    - name: Extraer aplicacion 2048
      ansible.builtin.unarchive:
        src: "~/Downloads/2048.tar.bz2"
        dest: "/var/www/html"
        owner: root
        group: root