---
# tasks file for dbserver
- name: Ejecucion en debian
  when: ansible_facts['os_family'] == 'Debian'
  import_tasks: install-debian.yml

- name: Ejecucion en Redhat
  when: ansible_facts['os_family'] == 'RedHat'
  import_tasks: install-redhat.yml