---
# tasks file for webserver
- name: Ejecucion en debian
  when: ansible_facts['os_family'] == 'Debian'
  ansible.builtin.include_tasks: install-debian.yml

- name: Ejecucion en Redhat
  when: ansible_facts['os_family'] == 'RedHat'
  ansible.builtin.include_tasks: install-redhat.yml